spring:
  application:
    name: CashVaultAPI
  datasource:
    url: YOUR_CONNECTION_STRING_HERE
    username: USERNAME
    password: PASSWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
  google:
    cloud:
      storage:
        credentials:
          location: storage-key.json
  spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: EMAIL ADDRESS
    password: SMTP GOOGLE EMAIL PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: FROM EMAIL ADDRESS



